# Generated by Django 2.0.7 on 2018-07-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albumes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Replicas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
    ]
