# Generated by Django 2.0.7 on 2018-08-14 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda', '0003_auto_20180814_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='perfiles'),
        ),
    ]
