# Generated by Django 2.0.7 on 2018-08-29 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banda', '0005_auto_20180829_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='albumes',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='banda.Albumes'),
            preserve_default=False,
        ),
    ]
