# Generated by Django 2.0.7 on 2018-08-29 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banda', '0006_producto_albumes'),
    ]

    operations = [
        migrations.AddField(
            model_name='replicas',
            name='productos',
            field=models.ManyToManyField(blank=True, null=True, to='banda.Producto'),
        ),
    ]
